
CREATE DATABASE IF NOT EXISTS crud;

USE crud;

CREATE TABLE IF NOT EXISTS herramientas(
    id INT NOT NULL AUTO_INCREMENT,
    nombre NVARCHAR(255) NOT NULL,
    material VARCHAR(255) NOT NULL DEFAULT '',
    precio VARCHAR(10) NULL,
    creado TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY( id )
);


